apiVersion: v1
kind: Service
metadata:
  name: example-book-service
spec:
  selector:
    app: example-book-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
